services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - qdrant
    restart: unless-stopped

  ingestion:
    build: ./ingestion-service
    container_name: ingestion
    depends_on:
      - qdrant
      - n8n
      - redis
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - N8N_LOG_WEBHOOK=http://n8n:5678/webhook/log
      - SENTENCE_MODEL=iZyphraLaw/legalbert-embedding
    env_file:
      - ./ingestion-service/.env         # 👈 This loads your Hugging Face model vars
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --log-level info --reload
    restart: unless-stopped
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface


  streamlit:
    build: ./streamlit-app
    container_name: streamlit
    ports:
      - "8501:8501"
    environment:
      - N8N_LOG_WEBHOOK=http://n8n:5678/webhook/log
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - n8n
      - redis
      - qdrant
      - ingestion
    restart: unless-stopped

  redis:
    image: redis:7
    command: ["redis-server", "--save", "900", "1", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  qdrant_data:
  n8n_data:
  redis-data:
