version: "3.8"

services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - chromadb
    restart: unless-stopped

  embedder:
    build: ./embedder-service
    container_name: embedder
    ports:
      - "5000:5000"
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    restart: unless-stopped

  ingestion:
    build: ./ingestion-service
    container_name: ingestion
    depends_on:
      - embedder
      - chromadb
    ports:
      - "8001:8001"
    restart: unless-stopped


  streamlit:
    build: ./streamlit-app
    container_name: streamlit
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - n8n
      - chromadb
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  chroma_data:
  n8n_data:
  ollama_data:
