apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
spec:
  replicas: 3  # 🔁 Multiple instances
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: ingestion-service:latest
          imagePullPolicy: Never  # If you're using local builds
          ports:
            - containerPort: 8001
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: N8N_LOG_WEBHOOK
              value: "http://n8n:5678/webhook/log"
          command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--log-level", "info", "--reload"]
          volumeMounts:
            - mountPath: /root/.cache/huggingface
              name: huggingface-cache
      volumes:
        - name: huggingface-cache
          emptyDir: {}
