services:
  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  crawler:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_DIR=/logs
    volumes:
      - ./logs:/logs
      - ./downloads:/data

volumes:
  redis-data:
