
services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kenya-law-crawler
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_DIR=/app/logs
      - CRAWL_START_URL=http://www.kenyalaw.org/lex//index.xql
      - CRAWL_MAX_DEPTH=5
      - CRAWL_MAX_WORKERS=5
      - CRAWL_OUTPUT=/app/output
      - USER_AGENT=Mozilla/5.0
      - TIMEOUT=10
      - RETRY_COUNT=3
      - RATE_LIMIT_DELAY=1
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output
    command: ["python", "-m", "src.main"]

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
